interface major {
  title: string;
  id: number;
}
const majors: Array<major> = [
  { title: 'Architectural Studies', id: 20 },
  { title: 'Architectural History', id: 21 },
  { title: 'Architecture', id: 22 },
  { title: 'Architectural Engineering', id: 23 },
  { title: 'Interior Design', id: 24 },
  { title: 'Accounting', id: 25 },
  { title: 'BHP', id: 26 },
  { title: 'Finance', id: 27 },
  { title: 'IMPA', id: 28 },
  { title: 'International Business', id: 29 },
  { title: 'Management', id: 31 },
  { title: 'Management Information System (MIS)', id: 32 },
  { title: 'Marketing', id: 33 },
  { title: 'Science & Technology Management (STM)', id: 34 },
  { title: 'Supply-Chain Management', id: 35 },
  { title: 'Business (Undeclared)', id: 38 },
  { title: 'Advertising', id: 39 },
  { title: 'Communication and Leadership', id: 40 },
  { title: 'Communication Studies', id: 41 },
  { title: 'Corporate Communication', id: 42 },
  { title: 'Human Relations', id: 43 },
  { title: 'Political Communication', id: 44 },
  { title: 'Communication Sciences and Disorders', id: 45 },
  { title: 'Audiology', id: 46 },
  { title: 'Education of the Deaf/Hearing Impaired', id: 47 },
  { title: 'Speech/Language Pathology', id: 48 },
  { title: 'Journalism', id: 49 },
  { title: 'Public Relations', id: 50 },
  { title: 'Radio-Television-Film', id: 51 },
  { title: 'Communications (Undeclared)', id: 52 },
  { title: 'Applied Learning and Development', id: 53 },
  { title: 'Early Childhood to Grade 6 Generalist', id: 54 },
  {
    title: 'Early Childhood to Grade 6 Bilingual Generalist Certification',
    id: 55,
  },
  { title: 'All-Level Generic Special Education', id: 56 },
  { title: 'Youth and Community Studies', id: 57 },
  { title: 'Athletic Training', id: 58 },
  { title: 'Kinesiology and Health Education', id: 59 },
  { title: 'Applied Movement Science', id: 60 },
  { title: 'Exercise Science', id: 61 },
  { title: 'Health Promotion and Behavioral Science', id: 62 },
  { title: 'Physical Culture and Sports', id: 63 },
  { title: 'Sport Management', id: 64 },
  { title: 'Aerospace Engineering', id: 65 },
  { title: 'Biomedical Engineering', id: 67 },
  { title: 'Chemical Engineering', id: 68 },
  { title: 'Civil Engineering', id: 69 },
  { title: 'Computational Engineering', id: 70 },
  { title: 'Electrical and Computer Engineering', id: 71 },
  { title: 'Environmental Engineering', id: 72 },
  { title: 'Geosystems Engineering and Hydrogeology', id: 73 },
  { title: 'Mechanical Engineering', id: 74 },
  { title: 'Petroleum Engineering', id: 75 },
  { title: 'Acting', id: 76 },
  { title: 'Art History', id: 77 },
  { title: 'Arts and Entertainment Technologies', id: 78 },
  { title: 'Dance', id: 79 },
  { title: 'Dance Studies', id: 80 },
  { title: 'Design', id: 81 },
  { title: 'Jazz', id: 82 },
  { title: 'Music', id: 83 },
  { title: 'Music Composition', id: 84 },
  { title: 'Music Performance', id: 85 },
  { title: 'Music Studies', id: 86 },
  { title: 'Choral Music Emphasis', id: 87 },
  { title: 'Instrumental Emphasis', id: 88 },
  { title: 'Studio Art', id: 89 },
  { title: 'Theatre and Dance', id: 90 },
  { title: 'Theatre Studies', id: 91 },
  { title: 'Visual Art Studies', id: 92 },
  { title: 'Environmental Science (Geological Sciences)', id: 93 },
  { title: 'Geological Sciences', id: 94 },
  { title: 'General', id: 95 },
  { title: 'Geophysics', id: 96 },
  { title: 'Hydrogeology', id: 97 },
  { title: 'Teaching', id: 98 },
  { title: 'African and African Diaspora Studies', id: 100 },
  { title: 'American Studies', id: 101 },
  { title: 'Anthropology', id: 102 },
  { title: 'Asian Cultures and Languages', id: 103 },
  { title: 'Chinese', id: 104 },
  { title: 'Hindi/Urdu', id: 105 },
  { title: 'Japanese', id: 106 },
  { title: 'Korean', id: 107 },
  { title: 'Malayalam', id: 108 },
  { title: 'Sanskrit', id: 109 },
  { title: 'Tamil', id: 110 },
  { title: 'Asian Studies', id: 111 },
  { title: 'East Asia', id: 112 },
  { title: 'South Asia', id: 113 },
  { title: 'Taiwan', id: 114 },
  { title: 'Classical Languages', id: 115 },
  { title: 'Classics', id: 116 },
  { title: 'Greek', id: 117 },
  { title: 'Latin', id: 118 },
  { title: 'Classical Studies', id: 119 },
  { title: 'Ancient History', id: 120 },
  { title: 'Classical Archaeology', id: 121 },
  { title: 'Economics', id: 122 },
  { title: 'English', id: 123 },
  { title: 'Environmental Science (Geographical Sciences)', id: 124 },
  { title: 'Ethnic Studies', id: 125 },
  { title: 'Asian American', id: 126 },
  { title: 'Mexican American', id: 127 },
  { title: 'European Studies', id: 128 },
  { title: 'French', id: 129 },
  { title: 'Geography', id: 130 },
  { title: 'German', id: 131 },
  { title: 'German, Scandinavian and Dutch Studies', id: 132 },
  { title: 'Government', id: 133 },
  { title: 'Health and Society', id: 134 },
  { title: 'History', id: 135 },
  { title: 'Human Dimensions of Organizations', id: 136 },
  { title: 'Humanities', id: 137 },
  { title: 'Iberian and Latin American Languages and Cultures', id: 138 },
  { title: 'International Relations and Global Studies', id: 139 },
  { title: 'Islamic Studies', id: 140 },
  { title: 'Italian', id: 141 },
  { title: 'Jewish Studies', id: 142 },
  { title: 'Latin American Studies', id: 143 },
  { title: 'Linguistics', id: 144 },
  { title: 'Middle Eastern Languages and Cultures', id: 145 },
  { title: 'Middle Eastern Studies', id: 146 },
  { title: 'Philosophy', id: 147 },
  { title: 'Plan II Honors Program', id: 148 },
  { title: 'Psychology', id: 149 },
  { title: 'Religious Studies', id: 150 },
  { title: 'Rhetoric and Writing', id: 151 },
  { title: 'Russian, East European and Eurasian Studies', id: 152 },
  { title: 'Sociology', id: 153 },
  { title: 'Sustainability Studies', id: 154 },
  { title: 'Liberal Arts (Undeclared)', id: 155 },
  { title: 'Urban Studies', id: 156 },
  { title: 'Women’s and Gender Studies', id: 157 },
  { title: 'Astronomy', id: 158 },
  { title: 'Biochemistry', id: 159 },
  { title: 'Biology', id: 160 },
  { title: 'Cell and Molecular Biology', id: 161 },
  { title: 'Computational Biology', id: 162 },
  { title: 'Ecology, Evolution and Behavior', id: 163 },
  { title: 'Human Biology', id: 164 },
  { title: 'Marine and Freshwater Science', id: 165 },
  { title: 'Microbiology and Infectious Diseases', id: 166 },
  { title: 'Plant Biology', id: 167 },
  { title: 'Chemistry', id: 169 },
  { title: 'Computation', id: 170 },
  { title: 'Computer Science', id: 172 },
  { title: 'Environmental Science (Biological Sciences)', id: 173 },
  { title: 'Human Development and Family Sciences', id: 174 },
  { title: 'Early Childhood', id: 175 },
  { title: 'Families and Personal Relationships', id: 176 },
  { title: 'Families and Society', id: 177 },
  { title: 'Human Development', id: 178 },
  { title: 'Human Ecology', id: 179 },
  { title: 'Mathematics', id: 180 },
  { title: 'Actuarial Science', id: 181 },
  { title: 'Applied Mathematics', id: 182 },
  { title: 'Mathematical Sciences', id: 183 },
  { title: 'Pure Mathematics', id: 184 },
  { title: 'Medical Laboratory Science', id: 186 },
  { title: 'Neuroscience', id: 187 },
  { title: 'Nutrition', id: 188 },
  { title: 'Dietetics', id: 189 },
  { title: 'International Nutrition', id: 190 },
  { title: 'Nutritional Sciences', id: 191 },
  { title: 'Nutrition and Public Health', id: 192 },
  { title: 'Physics', id: 193 },
  { title: 'BSA', id: 194 },
  { title: 'Biophysics', id: 195 },
  { title: 'Radiation Physics', id: 197 },
  { title: 'Space Sciences', id: 198 },
  { title: 'Pre-Pharmacy', id: 200 },
  { title: 'Public Health', id: 201 },
  { title: 'Textiles and Apparel', id: 202 },
  { title: 'Merchandising and Consumer Sciences', id: 203 },
  { title: 'Apparel, Functional and Technical Design', id: 204 },
  { title: 'CNS (Undeclared)', id: 205 },
  { title: 'Nursing', id: 206 },
  { title: 'Pharmacy', id: 207 },
  { title: 'Social Work', id: 208 },
  { title: 'Undeclared', id: 209 },
];

export default majors;
