const OUTER_STACK = 'OUTER_STACK';
const OUTER_STACK_MODAL = 'OUTER_STACK_MODAL';
const AUTH_SCREEN = 'AUTH_SCREEN';
const WELCOME_SCREEN = 'WELCOME_SCREEN';
const LOGIN_SCREEN = 'LOGIN_SCREEN';
const AUTH = 'AUTH';
const INNER_STACK = 'INNER_STACK';
const BROWSE_CARDS_SCREEN = 'BROWSE_CARDS_SCREEN';
const BROWSE_CARDS_STACK = 'BROWSE_CARDS_STACK';
const MESSAGES_SCREEN = 'MESSAGING_SCREEN';
const CHATS_SCREEN = 'CHATS_SCREEN';
const CHATS_STACK = 'CHATS_STACK';
const REGISTER_SCREEN = 'REGISTER_SCREEN';
const REQUESTS_SCREEN = 'REQUESTS_SCREEN';
const REQUESTS_STACK = 'REQUESTS_STACK';
const RECEPTION_STACK = 'RECEPTION_STACK';
const PROFILE_STACK = 'PROFILE_STACK';
const HOME_TABS = 'HOME_TABS';
const SETTINGS_STACK = 'SETTINGS_STACK';
const SETTINGS_SCREEN = 'SETTINGS_SCREEN';
const PROFILE_SCREEN = 'PROFILE_SCREEN';
const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN';
const WIDGET_GIPHY_SCREEN = 'WIDGET_GIPHY_SCREEN';

const REPORT_BUG_SCREEN = 'REPORT_BUG_SCREEN';
const ABOUT_US_SCREEN = 'ABOUT_US_SCREEN';
const VERIFY_SCREEN = 'VERIFY_SCREEN';
const CHANGE_PASSWORD_SCREEN = 'CHANGE_PASSWORD_SCREEN';

const TEST_SCREEN = 'TEST_SCREEN';
const WAITLIST_SCREEN = 'WAITLIST_SCREEN';
const WAITLIST_STACK = 'WAITLIST_STACK';
const NATIONAL = 'NATIONAL';
const QUIZ_STACK = 'QUIZ_STACK';
const QUIZ_TAKE_SCREEN = 'QUIZ_TAKE_SCREEN';
const QUIZ_SCREEN = 'QUIZ_SCREEN';
const MAP_TAB = 'MAP_TAB';
const CREATEPOPIN_SCREEN = 'CREATEPOPIN_SCREEN';
const POPINDETAILS_SCREEN = 'POPINDETAILS_SCREEN';
export default {
  AUTH,
  OUTER_STACK,
  TEST_SCREEN,
  SETTINGS_STACK,
  OUTER_STACK_MODAL,
  BROWSE_CARDS_STACK,
  CHANGE_PASSWORD_SCREEN,
  FORGOT_PASSWORD_SCREEN,
  INNER_STACK,
  WELCOME_SCREEN,
  VERIFY_SCREEN,
  CHATS_STACK,
  REQUESTS_STACK,
  LOGIN_SCREEN,
  AUTH_SCREEN,
  PROFILE_STACK,
  REPORT_BUG_SCREEN,
  BROWSE_CARDS_SCREEN,
  MESSAGES_SCREEN,
  PROFILE_SCREEN,
  CHATS_SCREEN,
  REGISTER_SCREEN,
  HOME_TABS,
  ABOUT_US_SCREEN,
  SETTINGS_SCREEN,
  REQUESTS_SCREEN,
  RECEPTION_STACK,
  WIDGET_GIPHY_SCREEN,
  WAITLIST_SCREEN,
  WAITLIST_STACK,
  NATIONAL,
  QUIZ_STACK,
  QUIZ_SCREEN,
  QUIZ_TAKE_SCREEN,
  MAP_TAB,
  CREATEPOPIN_SCREEN,
  POPINDETAILS_SCREEN,
};
