export const USER_UPDATE_PROFILE = 'user/UPDATE_PROFILE';
export const USER_UPDATE_PROFILE_FAILURE = 'user/UPDATE_PROFILE_FAILURE';
export const USER_UPDATE_PROFILE_SUCCESS = 'user/UPDATE_PROFILE_SUCCESS';

export const USER_GET_PROFILE = 'user/GET_PROFILE';
export const USER_GET_PROFILE_FAILURE = 'user/GET_PROFILE_FAILURE';
export const USER_GET_PROFILE_SUCCESS = 'user/GET_PROFILE_SUCCESS';

export const GET_USERS = 'user/GET_USERS';
export const GET_USERS_SUCCESS = 'user/GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'user/GET_USERS_FAILURE';

export const USER_SET_SETTING_SNOOZE = 'user/SET_SETTING_SNOOZE';

export const GET_QUIZZES = 'user/GET_QUIZZES';
export const GET_QUIZZES_SUCCESS = 'user/GET_QUIZZES_SUCCESS';
export const GET_QUIZZES_FAILURE = 'user/GET_QUIZZES_FAILURE';

export const GET_QUIZ = 'user/GET_QUIZ';
export const GET_QUIZ_SUCCESS = 'user/GET_QUIZ_SUCCESS';
export const GET_QUIZ_FAILURE = 'user/GET_QUIZ_FAILURE';

export const SUBMIT_QUIZ = 'user/SUBMIT_QUIZ';
export const SUBMIT_QUIZ_SUCCESS = 'user/SUBMIT_QUIZ_SUCCESS';
export const SUBMIT_QUIZ_FAILURE = 'user/SUBMIT_QUIZ_FAILURE';

export const GET_QUIZ_RESULT = 'user/GET_QUIZ_RESULT';
export const GET_QUIZ_RESULT_SUCCESS = 'user/GET_QUIZ_RESULT_SUCCESS';
export const GET_QUIZ_RESULT_FAILURE = 'user/GET_QUIZ_RESULT_FAILURE';

export const GET_QUIZ_PERSONALITY_RECOMMENDATION =
  'user/GET_QUIZ_PERSONALITY_RECOMMENDATION';
export const GET_QUIZ_PERSONALITY_RECOMMENDATION_SUCCESS =
  'user/GET_QUIZ_PERSONALITY_RECOMMENDATION_SUCCESS';
export const GET_QUIZ_PERSONALITY_RECOMMENDATION_FAILURE =
  'user/GET_QUIZ_PERSONALITY_RECOMMENDATION_FAILURE';

export const SELECT_QUIZ = 'user/SELECT_QUIZ';
export const SHOW_REPORT_BLOCK_MODAL = 'user/SHOW_REPORT_BLOCK_MODAL_OPEN';
export const SET_BLOCKED_USERS_LIST = 'user/SET_BLOCKED_USERS_LIST';
export const BLOCK_USER = 'user/BLOCK_USER';
export const UNBLOCK_USER = 'user/UNBLOCK_USER';
export const HIDE_PROFILE = 'user/HIDE_PROFILE';

export const SET_IS_VACCINATED = 'user/SET_IS_VACCINATED';
export const SET_VACCINATED_MODAL_SEEN = 'user/SET_VACCINATED_MODAL_SEEN';
